# Generated by Django 5.1.2 on 2025-02-27 04:45

import app1.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catering_name', models.CharField(max_length=255)),
                ('food_quality', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('service_quality', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('Cleanliness', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('Affordable', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('overall_satisfaction', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('description', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('content', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('instructor', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('materials', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('satisfaction', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('description', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=255)),
                ('behavior', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('knowledge', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('interaction', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('clarity', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('response', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('examples', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('motivation', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('satisfaction', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('description', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Infrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrastructure_name', models.CharField(max_length=255)),
                ('quality', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('resources', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('maintenance', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('safety', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('satisfaction', models.PositiveSmallIntegerField(validators=[app1.models.validate_rating])),
                ('description', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
