# Generated by Django 5.1.2 on 2025-01-21 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_infrastructure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
