# Generated by Django 5.1.2 on 2025-01-21 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='student',
            new_name='Trainee',
        ),
        migrations.RenameField(
            model_name='infrastructure',
            old_name='user',
            new_name='Trainee',
        ),
    ]
