# Generated by Django 5.1.2 on 2025-01-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_rename_student_faculty_trainee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
