# Generated by Django 5.1.2 on 2025-01-30 05:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_faculty_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='description',
            new_name='feedback_comments',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='Trainee',
            new_name='trainee',
        ),
        migrations.AddField(
            model_name='faculty',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rating',
            field=models.IntegerField(),
        ),
    ]
