# Generated by Django 5.1.2 on 2025-01-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_rename_description_faculty_feedback_comments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='faculty',
            old_name='trainee',
            new_name='Trainee',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='feedback_comments',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
    ]
