# Generated by Django 5.1.2 on 2025-01-31 06:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_rename_trainee_faculty_trainee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infrastructure',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=3, max_digits=5),
        ),
        migrations.AddField(
            model_name='infrastructure',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='Trainee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.user'),
        ),
    ]
