# Generated by Django 5.1.2 on 2025-01-31 06:45

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_infrastructure_rating_infrastructure_submitted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=5, validators=[app1.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='infrastructure',
            name='rating',
            field=models.DecimalField(decimal_places=0, default=3, max_digits=5, validators=[app1.models.validate_rating]),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
