# Generated by Django 5.1.2 on 2025-01-31 06:56

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_user_is_active_user_is_admin_user_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infrastructure',
            name='rating',
            field=models.DecimalField(decimal_places=0, max_digits=5, validators=[app1.models.validate_rating]),
        ),
    ]
