# Generated by Django 5.1.2 on 2025-02-03 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
