# Generated by Django 5.1.2 on 2025-02-04 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_catering'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
